[features]
seeds = false
[programs.localnet]
solana_twitter = "4yaEPf4xfKsLL3FfeD91f48EZUZxRaarERkAekhtsLTT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
